import { execFile } from 'node:child_process'
import { mkdtemp, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { promisify } from 'node:util'
import { describe, expect, test } from 'vitest'

const execFileAsync = promisify(execFile)

describe('npm package metadata', () => {
  test('supports npm installation with a bin entry and build lifecycle hooks', async () => {
    const packageJson = JSON.parse(await readFile('package.json', 'utf8')) as {
      name?: string
      private?: boolean
      bin?: Record<string, string>
      publishConfig?: Record<string, string>
      repository?: Record<string, string>
      scripts?: Record<string, string>
      version?: string
      files?: string[]
    }

    expect(packageJson.name).toBe('@feedmob/feedmob-pixel-cli')
    expect(packageJson.private).not.toBe(true)
    expect(packageJson.bin).toEqual({ fpc: 'dist/cli.js' })
    expect(packageJson.publishConfig).toEqual({
      access: 'public',
      registry: 'https://registry.npmjs.org/',
    })
    expect(packageJson.repository).toEqual({
      type: 'git',
      url: 'git+https://github.com/feed-mob/feedmob-pixel-cli.git',
    })
    expect(packageJson.scripts?.build).toBe('node ./scripts/generate-version.cjs && tsc -p tsconfig.json')
    expect(packageJson.scripts?.test).toBe('node ./scripts/generate-version.cjs && vitest run')
    expect(packageJson.scripts?.prepare).toBe('npm run build')
    expect(packageJson.scripts?.prepack).toBe('npm run build')
    expect(packageJson.scripts?.postinstall).toBe('node ./scripts/postinstall.cjs')
    expect(packageJson.files).toContain('dist')
    expect(packageJson.files).toContain('docs')
    expect(packageJson.files).toContain('scripts/postinstall.cjs')
  })

  test('generates the CLI version module from package metadata', async () => {
    const packageJson = JSON.parse(await readFile('package.json', 'utf8')) as {
      version?: string
    }
    const dir = await mkdtemp(join(tmpdir(), 'fpc-version-'))
    const out = join(dir, 'version.ts')

    await execFileAsync('node', ['scripts/generate-version.cjs'], {
      env: {
        ...process.env,
        FEEDPIX_GENERATED_VERSION_PATH: out,
      },
    })

    await expect(readFile(out, 'utf8')).resolves.toBe(
      `// Generated by scripts/generate-version.cjs. Do not edit manually.\nexport const CLI_VERSION = ${JSON.stringify(packageJson.version)}\n`,
    )
  })

  test('postinstall message prompts users to configure an API token', async () => {
    const { stdout } = await execFileAsync('node', ['scripts/postinstall.cjs'])

    expect(stdout).toContain('fpc installed - FeedMob Pixel Dashboard CLI')
    expect(stdout).toContain('Read-only Dashboard API queries')
    expect(stdout).toContain('FEEDMOB_DASHBOARD_API_TOKEN')
    expect(stdout).toContain('--token-env-var')
    expect(stdout).toContain('~/.fpc/config.json')
    expect(stdout).toContain('~/.fpc/.env')
    expect(stdout).toContain('fpc --version')
    expect(stdout).toContain('fpc --help')
    expect(stdout).toContain('fpc doctor')
    expect(stdout).toContain('fpc advertisers list')
    expect(stdout).not.toContain('--json')
    expect(stdout).toContain('https://github.com/feed-mob/feedmob-pixel-cli#readme')
  })
})
