#!/usr/bin/env node

const { mkdirSync, readFileSync, writeFileSync } = require('node:fs')
const { dirname, join } = require('node:path')

const repoRoot = join(__dirname, '..')
const packageJsonPath = join(repoRoot, 'package.json')
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
const version = packageJson.version

if (typeof version !== 'string' || version.length === 0) {
  throw new Error('package.json version must be a non-empty string')
}

const outPath =
  process.env.FEEDPIX_GENERATED_VERSION_PATH || join(repoRoot, 'src', 'generated', 'version.ts')
const content = `// Generated by scripts/generate-version.cjs. Do not edit manually.\nexport const CLI_VERSION = ${JSON.stringify(version)}\n`

mkdirSync(dirname(outPath), { recursive: true })

try {
  if (readFileSync(outPath, 'utf8') === content) {
    process.exit(0)
  }
} catch {
  // The file is created on the first build/test run.
}

writeFileSync(outPath, content)
