export const COMMAND_NAME = 'feedpix'
export const PROJECT_NAME = 'feedmob-pixel-cli'
export const CLI_VERSION = '0.1.0'
export const DASHBOARD_API_PREFIX = '/api/v1/dashboard_api'
export const DEFAULT_BASE_URL = 'https://feedmob-pixel-dashboard.feedmob.com/'
